#:schema node_modules/@deco/workers-runtime/config-schema.json
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
name = "e-summarizer"
scope = "candeia"

[deco]
enable_workflows = true
local = false

[deco.integration]
description = "MailMind is your smart email assistant that scans your inbox, summarizes important messages, and sends you a clean, human-friendly digest every day."
friendlyName = "MailMind"
icon = "https://assets.decocache.com/mcp/30f31730-89a0-4a97-8405-f35c674ebe7a/mailmind.png"

[[deco.bindings]]
name = "GMAIL"
type = "mcp"
integration_name = "@deco/google-gmail"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"