name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./apps/api
        run: |
          bun install
          
      - name: Install deco-cli
        run: |
          bun i -g deco-cli
      - name: Build
        run: npx wrangler deploy --dry-run --outdir ./dist

      - name: Run deco deploy
        run: deco deploy ./dist -y -t $DECO_DEPLOY_TOKEN --public
        env:
          DECO_DEPLOY_TOKEN: ${{ secrets.DECO_DEPLOY_TOKEN }}
